services:
  - type: web
    name: auto-text-editor-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    plan: free
buildCommand: PIP_NO_BUILD_ISOLATION=0 pip install -r requirements.txt
