services:
  - type: web
    name: auto-text-editor-web
    env: python
    plan: free
    buildCommand: PIP_NO_BUILD_ISOLATION=1 pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
build:
  pythonVersion: 3.9
